server:
  port: 8002
spring:
  datasource:
    url: jdbc:mysql://rm-uf67ktcrjo69g32viko.mysql.rds.aliyuncs.com:3306/reins?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: reins
    password: Reins5401
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
    jpa:
      database: mysql
      show-sql: false
  application:
    name: service-session-redis
  session:
    store-type: redis
    redis:
      namespace: demo:session
  redis:
    host: localhost
    port: 6380
    password: 123456
    timeout: 6000
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
    database: 0
#eureka:
#  client:
#    service-url: http://admin:123456@localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
